Release/dev
lgallard/terraform-aws-secrets-manager pull request #18
Opened 2021-12-10 02:50 UTC by bablubharath

2021-12-10 02:51 UTC, bablubharath commented
files ok

2021-12-10 03:00 UTC, bablubharath commented
ok

2022-01-02 22:01 UTC, lgallard requested changes

2022-01-02 22:01 UTC, lgallard commented on variables.tf
> +  default     = 7
@bablubharath it makes sense. Please remove the Jenkins file to merge this PR!

2022-01-02 22:01 UTC, lgallard commented on Jenkinsfile
> +pipeline {
@bablubharath why a Jenkins file in here? Can you remove it please?

2022-01-10 13:22 UTC, stevie- requested changes

2022-01-10 13:22 UTC, stevie- commented on providers.tf
> +}
Providers should not be present in modules. If aws provider is required one uses [required_providers](https://github.com/lgallard/terraform-aws-secrets-manager/blob/master/versions.tf#L4) setting

Delete this file.

2022-01-17 01:51 UTC, lgallard commented on providers.tf
> +}
Agree!

2022-01-27 20:50 UTC, lgallard commented
@bablubharath closing this PR. In case you want to include changes please consider the suggestions in this thread! Thanks!

2022-01-27 20:50 UTC, closed without merging